{% set name = "validate-pyproject" %}
{% set version = "0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c2d99f46fcba3231492ec39d0870fc6cba1415a0d89f2622fcb4a1d3d5a9f7bf

build:
  entry_points:
    - validate-pyproject=validate_pyproject.cli:main
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=46.1.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.7
    - python-fastjsonschema >=2.16.2,<=3
    - importlib-resources
    - importlib-metadata

test:
  imports:
    - validate_pyproject
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abravalheri/validate-pyproject/
  summary: Validation library and CLI tool for checking on pyproject.toml files using JSON Schema
  dev_url: https://github.com/abravalheri/validate-pyproject
  license: BSD-3-Clause AND MIT AND MPL-2.0
  license_file:
    - NOTICE.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
