{% set name = "validate-pyproject" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2e6de2f35d292d355cf2c3e636d8ee1e2ba713619d2e8179366c741a2c3d2077

build:
  entry_points:
    - validate-pyproject=validate_pyproject.cli:main
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=46.1.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.7
    - python-fastjsonschema >=2.16.2,<=3
    - importlib-resources
    - importlib-metadata

test:
  imports:
    - validate_pyproject
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abravalheri/validate-pyproject/
  summary: Validation library and CLI tool for checking on pyproject.toml files using JSON Schema
  dev_url: https://github.com/abravalheri/validate-pyproject
  license: BSD-3-Clause AND MIT AND MPL-2.0
  license_file:
    - NOTICE.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
